[package]
name = "downwards-content"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
downwards-core.workspace = true
downwards-gen.workspace = true

[dev-dependencies]
downwards-ai.workspace = true
serde_json = "=1.0.151"

[lib]
path = "src/lib.rs"
