//! Snapshot every palette course's tile grid into the ASCII room-grid format.
//!
//! Writes one `rooms/<slug>.txt` per course plus the generated
//! `src/room_grids.rs` include table, verifying each grid round-trips through
//! the parser before anything is written.
//!
//! Run from the workspace root with:
//! `cargo run -p downwards-gen --example export_room_grids`

use std::{fs, path::PathBuf};

use downwards_gen::{DungeonPaletteCourse, DungeonPaletteKey, parse_room_grid, render_room_grid};

fn main() {
    let crate_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let rooms_dir = crate_root.join("rooms");
    fs::create_dir_all(&rooms_dir).expect("create rooms directory");

    let mut table = String::from(
        "//! Generated by `cargo run -p downwards-gen --example export_room_grids`.\n//! Edit the grids under `rooms/`; regenerate this table only when rooms are\n//! added, removed, or renamed.\n\n/// ASCII tile grid source for every palette course, keyed by slug.\npub(crate) const ROOM_GRIDS: &[(&str, &str)] = &[\n",
    );
    for course in DungeonPaletteCourse::ALL {
        let candidate = DungeonPaletteKey::new(0, course).generate();
        let rendered = render_room_grid(candidate.tiles());
        assert_eq!(
            parse_room_grid(&rendered),
            candidate.tiles(),
            "{} grid must round-trip",
            course.slug()
        );
        fs::write(rooms_dir.join(format!("{}.txt", course.slug())), &rendered)
            .expect("write room grid");
        table.push_str(&format!(
            "    (\"{slug}\", include_str!(\"../rooms/{slug}.txt\")),\n",
            slug = course.slug()
        ));
    }
    table.push_str("];\n");
    fs::write(crate_root.join("src/room_grids.rs"), table).expect("write room grid table");
    eprintln!(
        "wrote {} grids and src/room_grids.rs",
        DungeonPaletteCourse::ALL.len()
    );
}
