[package]
name = "downwards-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
downwards-core.workspace = true
cpal = { version = "=0.18.2", optional = true }

[features]
default = ["live"]
live = ["dep:cpal"]

[lib]
path = "src/lib.rs"
