[package]
name = "downwards-catalogue"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
downwards-ai.workspace = true
downwards-core.workspace = true
downwards-gen.workspace = true
downwards-validation.workspace = true

[lib]
path = "src/lib.rs"
